#############################################################
# This ServiceNow-created file contains the path to the app in this repo
# path=<path to app content in your repo>
# For example, if the app content resides in a folder named x_my_custom_app, the path value would be:
# path=/x_my_custom_app
# Update the path value when you move the app to a new repo location.
############################################################
#
#Mon Sep 21 06:44:17 PDT 2026
path=48845d94c3e783102b587f65e4013123
